# Use the official Python 3.9 slim image as base image
FROM python:3.9-slim

# Set the working directory inside the container
WORKDIR /jan24_mlops_firebrigade

# Copy the test scripts into the container's working directory
COPY tests/ /jan24_mlops_firebrigade/tests/

# Install pytest and other dependencies
RUN pip install pytest

# Command to execute when the container starts
CMD ["pytest", "tests/"]
