version: '3'

services:
  preprossing:
    build:
      context: .
      dockerfile: Dockerfile_preprosseing
    image: preprossing
    volumes:
      - type: bind
        source: ./data/raw
        target: /app/data/raw
      - type: bind
        source: ./data/external
        target: /app/data/external
      - type: bind
        source: ./data/processed
        target: /app/data/processed



