version: '3'

services:
  preprossing:
    build:
      context: .
      dockerfile: Dockerfile_preprosseing
    image: preprossing
    volumes:
      - type: bind
        source: ./data/raw
        target: /jan24_mlops_firebrigade/data/raw
      - type: bind
        source: ./data/external
        target: /jan24_mlops_firebrigade/data/external
      - type: bind
        source: ./data/processed
        target: /jan24_mlops_firebrigade/data/processed
    networks:
      - firebrigade

  pytest:
    build:
      context: .
      dockerfile: Dockerfile_pytest
    depends_on:
      - preprossing
    volumes:
      - type: bind
        source: ./tests
        target: /jan24_mlops_firebrigade/tests
    networks:
      - firebrigade

networks:
  firebrigade:




