version: '3.9'

services:
  api:
    build: 
      context: . # Pfad zum Verzeichnis, das das Dockerfile_api enth채lt
      dockerfile: Dockerfile_api1 # Name des Dockerfiles f체r die API
    container_name: api
    volumes:
      - type: bind
        source: ./src/features
        target: /jan24_mlops_firebrigade/src/features
      - type: bind
        source: ./models
        target: /jan24_mlops_firebrigade/models
      - type: bind
        source: ./data/processed
        target: /jan24_mlops_firebrigade/data/processed
    command: ["uvicorn", "src.features.login_predict_jr:app", "--host", "0.0.0.0", "--port", "8000", "--reload"]

    networks:
      - my_bridge
    restart: on-failure  # Korrigierte Einr체ckung

  web:
    build: 
      context: . # Korrigierter Pfad, entferne das Leerzeichen vor dem "/"
      dockerfile: Dockerfile_eestream # Name des Dockerfiles f체r die Streamlit-Anwendung
    ports:
      - "8501:8501"
    depends_on:
      - api
    networks:
      - my_bridge

networks:
  my_bridge:
    driver: bridge
