# Use a base image with Python
FROM python:3.9

# Install the required dependencies
RUN pip install pyproj matplotlib numpy pandas geopy

# Copy the Python script into the container
COPY src/features/jr_preprossing.py /jan24_mlops_firebrigade/src/features/jr_preprossing.py

# Set the working directory inside the container
WORKDIR /jan24_mlops_firebrigade

# Command to run the script
CMD ["python", "src/features/jr_preprossing.py"]



